rulesets:
  - clazz: pl.klolo.archtests.example.rules.IntegrationTestsRuleSet
    applyTo: pl.klolo.archtests.example.it

  - clazz: pl.klolo.archtests.example.rules.DomainModuleTestsRuleSet
    applyTo: pl.klolo.archtests.example.domain
    disabled:
#      - domain_classes_implements_Serializable